version: '3.9'

services:
  database:
    image: mysql:8.0.21
    container_name: mysql_db
    platform: linux/x86_64
    command: npm start
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "insta"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 15s
      retries: 5

  api:
    build: .
    container_name: api
    working_dir: /app-backend
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - 3001:3001
    restart: always
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3001"] 
      timeout: 15s
      retries: 5
    volumes:
      - .:/app_backend
    